"""
Sentiment analysis across the corpus.

Approach:
  - Use the pre-computed sentimentScore (1-5) from summary.json as
    the primary signal. This was generated by the source pipeline
    that produced these transcripts.
  - Per-utterance sentimentType (positive/negative/neutral) is also
    available in transcript.json. We use it for *trajectory* analysis:
    how sentiment changes through a call.
  - Validate the call-level scores against the per-utterance sentiment
    distribution to surface mislabeled calls (cheap sanity check).
"""

from __future__ import annotations

import pandas as pd


# Bucket the 1-5 score into human-readable bands
def sentiment_band(score: float) -> str:
    if score >= 4.0:
        return "positive"
    if score >= 3.0:
        return "mixed"
    if score >= 2.0:
        return "negative"
    return "very_negative"


def call_level_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate sentiment by call_type."""
    g = df.groupby("call_type")["sentiment_score"].agg(
        ["count", "mean", "median", "std", "min", "max"]
    ).round(2)
    return g


def utterance_sentiment_distribution(transcript) -> dict[str, float]:
    """
    Distribution of utterance-level sentiments for a single transcript.
    Returns proportions: {positive: 0.4, negative: 0.1, neutral: 0.5}
    """
    counts = {"positive": 0, "negative": 0, "neutral": 0}
    for u in transcript.utterances:
        s = u.get("sentimentType", "neutral").lower()
        if s in counts:
            counts[s] += 1
    total = sum(counts.values()) or 1
    return {k: v / total for k, v in counts.items()}


def validate_call_sentiment(transcripts: list, df: pd.DataFrame) -> pd.DataFrame:
    """
    Cheap consistency check: does the call-level sentimentScore agree with
    the per-utterance sentiment distribution?

    For each call we compute a derived score:
        derived = (% positive utterances) - (% negative utterances)

    A call labeled "very-positive" with a derived score < 0 is suspect.
    """
    rows = []
    for t in transcripts:
        dist = utterance_sentiment_distribution(t)
        derived_polarity = dist["positive"] - dist["negative"]
        rows.append({
            "meeting_id": t.meeting_id,
            "title": t.title,
            "labeled_score": t.sentiment_score,
            "labeled_sentiment": t.overall_sentiment,
            "pct_positive_utterances": dist["positive"],
            "pct_negative_utterances": dist["negative"],
            "pct_neutral_utterances": dist["neutral"],
            "derived_polarity": derived_polarity,
        })
    out = pd.DataFrame(rows)
    # Flag possible mismatches: labeled positive but more negative utterances
    out["mismatch_flag"] = (
        ((out.labeled_score >= 4) & (out.derived_polarity < 0)) |
        ((out.labeled_score <= 2) & (out.derived_polarity > 0.2))
    )
    return out


def call_trajectory(transcript) -> list[float]:
    """
    Sentiment trajectory through a call, in 10 equal time buckets.
    Each value is (% positive - % negative) of utterances in that bucket.
    Useful for spotting calls that 'turned around' or 'fell apart'.
    """
    utterances = transcript.utterances
    if not utterances:
        return [0.0] * 10
    n = len(utterances)
    bucket_size = max(1, n // 10)
    buckets = [utterances[i*bucket_size:(i+1)*bucket_size] for i in range(10)]
    # tail bucket gets remainder
    if n > bucket_size * 10:
        buckets[-1] += utterances[bucket_size*10:]
    out = []
    for b in buckets:
        if not b:
            out.append(0.0)
            continue
        pos = sum(1 for u in b if u.get("sentimentType") == "positive")
        neg = sum(1 for u in b if u.get("sentimentType") == "negative")
        out.append((pos - neg) / len(b))
    return out
